### PR TITLE
Switch to active_record_store for sessions

### PR DESCRIPTION
**Pull request by colinbm**
There is a 4kb limit on cookie sessions, which occasionally gets passed causing CookieOverflow exception.
Switching to database storage solves this.

```
ActionDispatch::Cookies::CookieOverflow: ActionDispatch::Cookies::CookieOverflow
  actionpack (6.0.3.4) lib/action_dispatch/middleware/cookies.rb:637:in `commit'
  actionpack (6.0.3.4) lib/action_dispatch/middleware/cookies.rb:472:in `[]='
  actionpack (6.0.3.4) lib/action_dispatch/middleware/session/cookie_store.rb:110:in `set_cookie'
  rack (2.2.3) lib/rack/session/abstract/id.rb:403:in `commit_session'
  rack (2.2.3) lib/rack/session/abstract/id.rb:268:in `context'
...
(32 additional frame(s) were not displayed)
```

### CODE REVIEW

**Comment by koetsier** [comment]
Any idea why the cookie overflow is triggered? Ideally we shouldn't use the session to store a whole lot of stuff

**Review by koetsier — CHANGES_REQUESTED** [review]
Can we find out the root cause of why the cookie overflow happens?

**Comment by colinbm** [comment]
Cause unclear. We talked at standup yesterday and the consensus was to get this fix in and add a card for further investigation to the board. We can more easily monitor typical session size too once they're in the database.

**Review by koetsier — APPROVED** [review]
lgtm 🎉

**Pull request merged**
