### PR TITLE
Use stylelint for scss

### PR DESCRIPTION
**Pull request by colinbm**
### What
Implement stylelint for linting `scss`

### Why
We don't currently lint `scss` and should.

Link to Trello card (if applicable): https://trello.com/c/BFKII4Iv

### CODE REVIEW

**Review by koetsier — COMMENTED** [review]
-

**Review by koetsier — CHANGES_REQUESTED** [review]
Did you look at https://github.com/alphagov/scss-lint-govuk? It seems it is half implemented because there is a .scss-lint.yml file, but the gem doesn't seem to be installed

**Comment by colinbm** [comment]
Ah I did not... that project is deprecated, though it's superseded by a stylelint config... so hopefully what I've done so far isn't wasted!

**Comment by koetsier** [comment]
> Ah I did not... that project is deprecated, though it's superseded by a stylelint config... so hopefully what I've done so far isn't wasted!

You're right - I didn't look properly. The config is hopefully useful though!

**Review by koetsier — APPROVED** [review]
Looks great!

**Pull request merged**
