### PR TITLE
Tidy up the create/switch organisation pages 

### PR DESCRIPTION
**Pull request by quis**
This PR removes stuff that is organisation-specific from pages which are not specific to an organisation (ie the pages you use to switch to another organisation, or to create an organisation).

It also fixes some broken things on the create organisation page:
- incorrect column width
- the [accessible autocomplete](https://github.com/alphagov/accessible-autocomplete) which wasn’t getting initialised 

# Before 

image

# After 

image

### CODE REVIEW

**Comment by freesteph** [comment]
sorry I meant to update through rebase, will fix.

**Comment by quis** [comment]
Should remove the navigation from the two-factor code pages as well. @freesteph let me know when you’re finished rebasing and I’ll tack that on to this PR.

**Comment by freesteph** [comment]
@quis all yours :+1:

**Comment by freesteph** [comment]
@quis since we'd introduced some layout changes in #904 I've had to rewrite a certain amount of code and have therefore opened a new PR at #928. I'm going to close this PR in favour of the new one which is a merge of our two branches, rebased against the current stack etc. Would you mind reviewing when you have time?

**Pull request closed without merging**
